// Generated by gencpp from file respeaker_ros/RawAudioData.msg
// DO NOT EDIT!


#ifndef RESPEAKER_ROS_MESSAGE_RAWAUDIODATA_H
#define RESPEAKER_ROS_MESSAGE_RAWAUDIODATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace respeaker_ros
{
template <class ContainerAllocator>
struct RawAudioData_
{
  typedef RawAudioData_<ContainerAllocator> Type;

  RawAudioData_()
    : header()
    , nb_channel(0)
    , rate(0)
    , format(0)
    , sample_byte_size(0)
    , nb_frames(0)
    , data()  {
    }
  RawAudioData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nb_channel(0)
    , rate(0)
    , format(0)
    , sample_byte_size(0)
    , nb_frames(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _nb_channel_type;
  _nb_channel_type nb_channel;

   typedef int32_t _rate_type;
  _rate_type rate;

   typedef int32_t _format_type;
  _format_type format;

   typedef int32_t _sample_byte_size_type;
  _sample_byte_size_type sample_byte_size;

   typedef int32_t _nb_frames_type;
  _nb_frames_type nb_frames;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::respeaker_ros::RawAudioData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::respeaker_ros::RawAudioData_<ContainerAllocator> const> ConstPtr;

}; // struct RawAudioData_

typedef ::respeaker_ros::RawAudioData_<std::allocator<void> > RawAudioData;

typedef boost::shared_ptr< ::respeaker_ros::RawAudioData > RawAudioDataPtr;
typedef boost::shared_ptr< ::respeaker_ros::RawAudioData const> RawAudioDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::respeaker_ros::RawAudioData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::respeaker_ros::RawAudioData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::respeaker_ros::RawAudioData_<ContainerAllocator1> & lhs, const ::respeaker_ros::RawAudioData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.nb_channel == rhs.nb_channel &&
    lhs.rate == rhs.rate &&
    lhs.format == rhs.format &&
    lhs.sample_byte_size == rhs.sample_byte_size &&
    lhs.nb_frames == rhs.nb_frames &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::respeaker_ros::RawAudioData_<ContainerAllocator1> & lhs, const ::respeaker_ros::RawAudioData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace respeaker_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::respeaker_ros::RawAudioData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respeaker_ros::RawAudioData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respeaker_ros::RawAudioData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c397debf40a72ecc26b4cfd85d2a668";
  }

  static const char* value(const ::respeaker_ros::RawAudioData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c397debf40a72ecULL;
  static const uint64_t static_value2 = 0xc26b4cfd85d2a668ULL;
};

template<class ContainerAllocator>
struct DataType< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "respeaker_ros/RawAudioData";
  }

  static const char* value(const ::respeaker_ros::RawAudioData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8   nb_channel\n"
"int32  rate\n"
"int32  format\n"
"int32  sample_byte_size\n"
"int32  nb_frames\n"
"int16[] data\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::respeaker_ros::RawAudioData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nb_channel);
      stream.next(m.rate);
      stream.next(m.format);
      stream.next(m.sample_byte_size);
      stream.next(m.nb_frames);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RawAudioData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::respeaker_ros::RawAudioData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::respeaker_ros::RawAudioData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nb_channel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.nb_channel);
    s << indent << "rate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rate);
    s << indent << "format: ";
    Printer<int32_t>::stream(s, indent + "  ", v.format);
    s << indent << "sample_byte_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sample_byte_size);
    s << indent << "nb_frames: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nb_frames);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESPEAKER_ROS_MESSAGE_RAWAUDIODATA_H
