// Generated by gencpp from file pal_navigation_msgs/GetWaypoint.msg
// DO NOT EDIT!


#ifndef PAL_NAVIGATION_MSGS_MESSAGE_GETWAYPOINT_H
#define PAL_NAVIGATION_MSGS_MESSAGE_GETWAYPOINT_H

#include <ros/service_traits.h>


#include <pal_navigation_msgs/GetWaypointRequest.h>
#include <pal_navigation_msgs/GetWaypointResponse.h>


namespace pal_navigation_msgs
{

struct GetWaypoint
{

typedef GetWaypointRequest Request;
typedef GetWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypoint
} // namespace pal_navigation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_navigation_msgs::GetWaypoint > {
  static const char* value()
  {
    return "a7a8a459ce4c4b9d51acc19ee16d34fd";
  }

  static const char* value(const ::pal_navigation_msgs::GetWaypoint&) { return value(); }
};

template<>
struct DataType< ::pal_navigation_msgs::GetWaypoint > {
  static const char* value()
  {
    return "pal_navigation_msgs/GetWaypoint";
  }

  static const char* value(const ::pal_navigation_msgs::GetWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::pal_navigation_msgs::GetWaypointRequest> should match
// service_traits::MD5Sum< ::pal_navigation_msgs::GetWaypoint >
template<>
struct MD5Sum< ::pal_navigation_msgs::GetWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_navigation_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::pal_navigation_msgs::GetWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_navigation_msgs::GetWaypointRequest> should match
// service_traits::DataType< ::pal_navigation_msgs::GetWaypoint >
template<>
struct DataType< ::pal_navigation_msgs::GetWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::pal_navigation_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::pal_navigation_msgs::GetWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_navigation_msgs::GetWaypointResponse> should match
// service_traits::MD5Sum< ::pal_navigation_msgs::GetWaypoint >
template<>
struct MD5Sum< ::pal_navigation_msgs::GetWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_navigation_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::pal_navigation_msgs::GetWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_navigation_msgs::GetWaypointResponse> should match
// service_traits::DataType< ::pal_navigation_msgs::GetWaypoint >
template<>
struct DataType< ::pal_navigation_msgs::GetWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::pal_navigation_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::pal_navigation_msgs::GetWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_NAVIGATION_MSGS_MESSAGE_GETWAYPOINT_H
