// Generated by gencpp from file pal_navigation_msgs/GetWaypointResponse.msg
// DO NOT EDIT!


#ifndef PAL_NAVIGATION_MSGS_MESSAGE_GETWAYPOINTRESPONSE_H
#define PAL_NAVIGATION_MSGS_MESSAGE_GETWAYPOINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pal_navigation_msgs/Waypoint.h>

namespace pal_navigation_msgs
{
template <class ContainerAllocator>
struct GetWaypointResponse_
{
  typedef GetWaypointResponse_<ContainerAllocator> Type;

  GetWaypointResponse_()
    : pose()  {
    }
  GetWaypointResponse_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::pal_navigation_msgs::Waypoint_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWaypointResponse_

typedef ::pal_navigation_msgs::GetWaypointResponse_<std::allocator<void> > GetWaypointResponse;

typedef boost::shared_ptr< ::pal_navigation_msgs::GetWaypointResponse > GetWaypointResponsePtr;
typedef boost::shared_ptr< ::pal_navigation_msgs::GetWaypointResponse const> GetWaypointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator1> & lhs, const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator1> & lhs, const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_navigation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7a8a459ce4c4b9d51acc19ee16d34fd";
  }

  static const char* value(const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7a8a459ce4c4b9dULL;
  static const uint64_t static_value2 = 0x51acc19ee16d34fdULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_navigation_msgs/GetWaypointResponse";
  }

  static const char* value(const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"pal_navigation_msgs/Waypoint pose\n"
"\n"
"================================================================================\n"
"MSG: pal_navigation_msgs/Waypoint\n"
"# Error codes\n"
"# Note: The expected priority order of the errors should match the message order\n"
"uint32 NOTHING=0\n"
"uint32 WAIT=1\n"
"uint32 ROTATE=2\n"
"uint32 DOCK=3\n"
"uint32 UNDOCK=4\n"
"\n"
"uint32[] actions\n"
"geometry_msgs/PoseStamped pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWaypointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_navigation_msgs::GetWaypointResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::pal_navigation_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_NAVIGATION_MSGS_MESSAGE_GETWAYPOINTRESPONSE_H
