// Generated by gencpp from file pal_navigation_msgs/TransformMapConfiguration.msg
// DO NOT EDIT!


#ifndef PAL_NAVIGATION_MSGS_MESSAGE_TRANSFORMMAPCONFIGURATION_H
#define PAL_NAVIGATION_MSGS_MESSAGE_TRANSFORMMAPCONFIGURATION_H

#include <ros/service_traits.h>


#include <pal_navigation_msgs/TransformMapConfigurationRequest.h>
#include <pal_navigation_msgs/TransformMapConfigurationResponse.h>


namespace pal_navigation_msgs
{

struct TransformMapConfiguration
{

typedef TransformMapConfigurationRequest Request;
typedef TransformMapConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransformMapConfiguration
} // namespace pal_navigation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_navigation_msgs::TransformMapConfiguration > {
  static const char* value()
  {
    return "23aa9750afc82f6179dccc19be33142b";
  }

  static const char* value(const ::pal_navigation_msgs::TransformMapConfiguration&) { return value(); }
};

template<>
struct DataType< ::pal_navigation_msgs::TransformMapConfiguration > {
  static const char* value()
  {
    return "pal_navigation_msgs/TransformMapConfiguration";
  }

  static const char* value(const ::pal_navigation_msgs::TransformMapConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::pal_navigation_msgs::TransformMapConfigurationRequest> should match
// service_traits::MD5Sum< ::pal_navigation_msgs::TransformMapConfiguration >
template<>
struct MD5Sum< ::pal_navigation_msgs::TransformMapConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_navigation_msgs::TransformMapConfiguration >::value();
  }
  static const char* value(const ::pal_navigation_msgs::TransformMapConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_navigation_msgs::TransformMapConfigurationRequest> should match
// service_traits::DataType< ::pal_navigation_msgs::TransformMapConfiguration >
template<>
struct DataType< ::pal_navigation_msgs::TransformMapConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::pal_navigation_msgs::TransformMapConfiguration >::value();
  }
  static const char* value(const ::pal_navigation_msgs::TransformMapConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_navigation_msgs::TransformMapConfigurationResponse> should match
// service_traits::MD5Sum< ::pal_navigation_msgs::TransformMapConfiguration >
template<>
struct MD5Sum< ::pal_navigation_msgs::TransformMapConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_navigation_msgs::TransformMapConfiguration >::value();
  }
  static const char* value(const ::pal_navigation_msgs::TransformMapConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_navigation_msgs::TransformMapConfigurationResponse> should match
// service_traits::DataType< ::pal_navigation_msgs::TransformMapConfiguration >
template<>
struct DataType< ::pal_navigation_msgs::TransformMapConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::pal_navigation_msgs::TransformMapConfiguration >::value();
  }
  static const char* value(const ::pal_navigation_msgs::TransformMapConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_NAVIGATION_MSGS_MESSAGE_TRANSFORMMAPCONFIGURATION_H
